/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActionStatusResponse,
  Modality,
} from '../models/index';
import {
    ActionStatusResponseFromJSON,
    ActionStatusResponseToJSON,
    ModalityFromJSON,
    ModalityToJSON,
} from '../models/index';

export interface DeleteRequest {
    vectorSpaceId: number;
    id?: Array<number>;
}

export interface ClearVectorSpaceRequest {
    vectorSpaceId: number;
}

export interface ClearVectorSpaceOldRequest {
    vectorSpaceId: number;
}

export interface UpdateAttributesRequest {
    vectorSpaceId: number;
    id?: Array<number>;
    attributes?: Array<string>;
}

export interface UpdateEmbeddingsRequest {
    vectorSpaceId: number;
    modality?: Modality;
    id?: Array<number>;
    input?: Array<Blob>;
}

/**
 * 
 */
export class UpdateApi extends runtime.BaseAPI {

    /**
     * Delete one or more elements.
     * Delete vector embeddings
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionStatusResponse>> {
        if (requestParameters.vectorSpaceId === null || requestParameters.vectorSpaceId === undefined) {
            throw new runtime.RequiredError('vectorSpaceId','Required parameter requestParameters.vectorSpaceId was null or undefined when calling _delete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("SecurityScheme", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = true;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.id) {
            formParams.append('id', requestParameters.id.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        const response = await this.request({
            path: `/api/v0/space/{vector_space_id}/delete`.replace(`{${"vector_space_id"}}`, encodeURIComponent(String(requestParameters.vectorSpaceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete one or more elements.
     * Delete vector embeddings
     */
    async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionStatusResponse> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete all entries and stored analogies within a vector space.
     * Delete all entries in a vector space
     */
    async clearVectorSpaceRaw(requestParameters: ClearVectorSpaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionStatusResponse>> {
        if (requestParameters.vectorSpaceId === null || requestParameters.vectorSpaceId === undefined) {
            throw new runtime.RequiredError('vectorSpaceId','Required parameter requestParameters.vectorSpaceId was null or undefined when calling clearVectorSpace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("SecurityScheme", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v0/space/{vector_space_id}/delete_all`.replace(`{${"vector_space_id"}}`, encodeURIComponent(String(requestParameters.vectorSpaceId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete all entries and stored analogies within a vector space.
     * Delete all entries in a vector space
     */
    async clearVectorSpace(requestParameters: ClearVectorSpaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionStatusResponse> {
        const response = await this.clearVectorSpaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete all entries and stored analogies within a vector space.
     * Delete all entries in a vector space
     */
    async clearVectorSpaceOldRaw(requestParameters: ClearVectorSpaceOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionStatusResponse>> {
        if (requestParameters.vectorSpaceId === null || requestParameters.vectorSpaceId === undefined) {
            throw new runtime.RequiredError('vectorSpaceId','Required parameter requestParameters.vectorSpaceId was null or undefined when calling clearVectorSpaceOld.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("SecurityScheme", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v0/space/{vector_space_id}/delete_all`.replace(`{${"vector_space_id"}}`, encodeURIComponent(String(requestParameters.vectorSpaceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete all entries and stored analogies within a vector space.
     * Delete all entries in a vector space
     */
    async clearVectorSpaceOld(requestParameters: ClearVectorSpaceOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionStatusResponse> {
        const response = await this.clearVectorSpaceOldRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update attributes of one or more elements.
     * Update vector attributes
     */
    async updateAttributesRaw(requestParameters: UpdateAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionStatusResponse>> {
        if (requestParameters.vectorSpaceId === null || requestParameters.vectorSpaceId === undefined) {
            throw new runtime.RequiredError('vectorSpaceId','Required parameter requestParameters.vectorSpaceId was null or undefined when calling updateAttributes.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("SecurityScheme", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = true;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.id) {
            formParams.append('id', requestParameters.id.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters.attributes) {
            formParams.append('attributes', requestParameters.attributes.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        const response = await this.request({
            path: `/api/v0/space/{vector_space_id}/update/attributes`.replace(`{${"vector_space_id"}}`, encodeURIComponent(String(requestParameters.vectorSpaceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionStatusResponseFromJSON(jsonValue));
    }

    /**
     * Update attributes of one or more elements.
     * Update vector attributes
     */
    async updateAttributes(requestParameters: UpdateAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionStatusResponse> {
        const response = await this.updateAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update embeddings of one or more elements.
     * Update vector embeddings
     */
    async updateEmbeddingsRaw(requestParameters: UpdateEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ActionStatusResponse>> {
        if (requestParameters.vectorSpaceId === null || requestParameters.vectorSpaceId === undefined) {
            throw new runtime.RequiredError('vectorSpaceId','Required parameter requestParameters.vectorSpaceId was null or undefined when calling updateEmbeddings.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("SecurityScheme", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = true;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.modality !== undefined) {
            formParams.append('modality', requestParameters.modality as any);
                    }

        if (requestParameters.id) {
            formParams.append('id', requestParameters.id.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters.input) {
            requestParameters.input.forEach((element) => {
                formParams.append('input', element as any);
            })
        }

        const response = await this.request({
            path: `/api/v0/space/{vector_space_id}/update/vectors`.replace(`{${"vector_space_id"}}`, encodeURIComponent(String(requestParameters.vectorSpaceId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ActionStatusResponseFromJSON(jsonValue));
    }

    /**
     * Update embeddings of one or more elements.
     * Update vector embeddings
     */
    async updateEmbeddings(requestParameters: UpdateEmbeddingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ActionStatusResponse> {
        const response = await this.updateEmbeddingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
