/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActionStatusResponse
 */
export interface ActionStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof ActionStatusResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the ActionStatusResponse interface.
 */
export function instanceOfActionStatusResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActionStatusResponseFromJSON(json: any): ActionStatusResponse {
    return ActionStatusResponseFromJSONTyped(json, false);
}

export function ActionStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function ActionStatusResponseToJSON(value?: ActionStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

