/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataEntry
 */
export interface DataEntry {
    /**
     * 
     * @type {number}
     * @memberof DataEntry
     */
    id?: number;
    /**
     * Arbitrary JSON value
     * @type {object}
     * @memberof DataEntry
     */
    attributes?: object;
}

/**
 * Check if a given object implements the DataEntry interface.
 */
export function instanceOfDataEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataEntryFromJSON(json: any): DataEntry {
    return DataEntryFromJSONTyped(json, false);
}

export function DataEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
    };
}

export function DataEntryToJSON(value?: DataEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'attributes': value.attributes,
    };
}

