/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteRequestDto
 */
export interface DeleteRequestDto {
    /**
     * id of the vector whose embeddings should be deleted
     * @type {Array<number>}
     * @memberof DeleteRequestDto
     */
    id?: Array<number>;
}

/**
 * Check if a given object implements the DeleteRequestDto interface.
 */
export function instanceOfDeleteRequestDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteRequestDtoFromJSON(json: any): DeleteRequestDto {
    return DeleteRequestDtoFromJSONTyped(json, false);
}

export function DeleteRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function DeleteRequestDtoToJSON(value?: DeleteRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

