/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Modality } from './Modality';
import {
    ModalityFromJSON,
    ModalityFromJSONTyped,
    ModalityToJSON,
} from './Modality';

/**
 * 
 * @export
 * @interface IndexRequestDto
 */
export interface IndexRequestDto {
    /**
     * 
     * @type {Modality}
     * @memberof IndexRequestDto
     */
    modality?: Modality;
    /**
     * Input attributes
     * @type {Array<string>}
     * @memberof IndexRequestDto
     */
    attributes?: Array<string>;
    /**
     * Input as binary data
     * @type {Array<Blob>}
     * @memberof IndexRequestDto
     */
    input?: Array<Blob>;
}

/**
 * Check if a given object implements the IndexRequestDto interface.
 */
export function instanceOfIndexRequestDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IndexRequestDtoFromJSON(json: any): IndexRequestDto {
    return IndexRequestDtoFromJSONTyped(json, false);
}

export function IndexRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modality': !exists(json, 'modality') ? undefined : ModalityFromJSON(json['modality']),
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'input': !exists(json, 'input') ? undefined : json['input'],
    };
}

export function IndexRequestDtoToJSON(value?: IndexRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'modality': ModalityToJSON(value.modality),
        'attributes': value.attributes,
        'input': value.input,
    };
}

