/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Modality = {
    Image: 'IMAGE',
    Text: 'TEXT'
} as const;
export type Modality = typeof Modality[keyof typeof Modality];


export function ModalityFromJSON(json: any): Modality {
    return ModalityFromJSONTyped(json, false);
}

export function ModalityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Modality {
    return json as Modality;
}

export function ModalityToJSON(value?: Modality | null): any {
    return value as any;
}

