/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VectoUsageMetrics } from './VectoUsageMetrics';
import {
    VectoUsageMetricsFromJSON,
    VectoUsageMetricsFromJSONTyped,
    VectoUsageMetricsToJSON,
} from './VectoUsageMetrics';

/**
 * 
 * @export
 * @interface MonthlyUsageResponse
 */
export interface MonthlyUsageResponse {
    /**
     * 
     * @type {number}
     * @memberof MonthlyUsageResponse
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlyUsageResponse
     */
    month?: number;
    /**
     * 
     * @type {VectoUsageMetrics}
     * @memberof MonthlyUsageResponse
     */
    usage?: VectoUsageMetrics;
}

/**
 * Check if a given object implements the MonthlyUsageResponse interface.
 */
export function instanceOfMonthlyUsageResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MonthlyUsageResponseFromJSON(json: any): MonthlyUsageResponse {
    return MonthlyUsageResponseFromJSONTyped(json, false);
}

export function MonthlyUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MonthlyUsageResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year': !exists(json, 'year') ? undefined : json['year'],
        'month': !exists(json, 'month') ? undefined : json['month'],
        'usage': !exists(json, 'usage') ? undefined : VectoUsageMetricsFromJSON(json['usage']),
    };
}

export function MonthlyUsageResponseToJSON(value?: MonthlyUsageResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': value.year,
        'month': value.month,
        'usage': VectoUsageMetricsToJSON(value.usage),
    };
}

