/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DailyUsageMetric } from './DailyUsageMetric';
import {
    DailyUsageMetricFromJSON,
    DailyUsageMetricFromJSONTyped,
    DailyUsageMetricToJSON,
} from './DailyUsageMetric';

/**
 * 
 * @export
 * @interface UsageMetric
 */
export interface UsageMetric {
    /**
     * 
     * @type {Array<DailyUsageMetric>}
     * @memberof UsageMetric
     */
    dailyMetrics?: Array<DailyUsageMetric>;
}

/**
 * Check if a given object implements the UsageMetric interface.
 */
export function instanceOfUsageMetric(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsageMetricFromJSON(json: any): UsageMetric {
    return UsageMetricFromJSONTyped(json, false);
}

export function UsageMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageMetric {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dailyMetrics': !exists(json, 'dailyMetrics') ? undefined : ((json['dailyMetrics'] as Array<any>).map(DailyUsageMetricFromJSON)),
    };
}

export function UsageMetricToJSON(value?: UsageMetric | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dailyMetrics': value.dailyMetrics === undefined ? undefined : ((value.dailyMetrics as Array<any>).map(DailyUsageMetricToJSON)),
    };
}

