/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsageMetric } from './UsageMetric';
import {
    UsageMetricFromJSON,
    UsageMetricFromJSONTyped,
    UsageMetricToJSON,
} from './UsageMetric';

/**
 * 
 * @export
 * @interface VectoUsageMetrics
 */
export interface VectoUsageMetrics {
    /**
     * 
     * @type {UsageMetric}
     * @memberof VectoUsageMetrics
     */
    lookups?: UsageMetric;
    /**
     * 
     * @type {UsageMetric}
     * @memberof VectoUsageMetrics
     */
    indexing?: UsageMetric;
}

/**
 * Check if a given object implements the VectoUsageMetrics interface.
 */
export function instanceOfVectoUsageMetrics(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VectoUsageMetricsFromJSON(json: any): VectoUsageMetrics {
    return VectoUsageMetricsFromJSONTyped(json, false);
}

export function VectoUsageMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectoUsageMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lookups': !exists(json, 'lookups') ? undefined : UsageMetricFromJSON(json['lookups']),
        'indexing': !exists(json, 'indexing') ? undefined : UsageMetricFromJSON(json['indexing']),
    };
}

export function VectoUsageMetricsToJSON(value?: VectoUsageMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lookups': UsageMetricToJSON(value.lookups),
        'indexing': UsageMetricToJSON(value.indexing),
    };
}

