name: Node.js CI

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Run npm test
    runs-on: ubuntu-latest

    env:
      TEST_VECTOR_SPACE_ID: ${{ secrets.TEST_VECTOR_SPACE_ID }}
      TEST_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.TEST_MANAGEMENT_ACCESS_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm ci

    - name: Set up environment variables
      run: |
        echo "TEST_MANAGEMENT_ACCESS_TOKEN=${{ secrets.TEST_MANAGEMENT_ACCESS_TOKEN }}" >> $GITHUB_ENV
        echo "TEST_VECTOR_SPACE_ID=${{ secrets.TEST_VECTOR_SPACE_ID }}" >> $GITHUB_ENV

    - name: Run tests
      run: npm test
