/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalogyDTO
 */
export interface AnalogyDTO {
    /**
     * 
     * @type {number}
     * @memberof AnalogyDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AnalogyDTO
     */
    name?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof AnalogyDTO
     */
    textAnalogyExampleIds?: Array<number>;
    /**
     * 
     * @type {Date}
     * @memberof AnalogyDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalogyDTO
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof AnalogyDTO
     */
    vectorSpaceId?: number;
}

/**
 * Check if a given object implements the AnalogyDTO interface.
 */
export function instanceOfAnalogyDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalogyDTOFromJSON(json: any): AnalogyDTO {
    return AnalogyDTOFromJSONTyped(json, false);
}

export function AnalogyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalogyDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'textAnalogyExampleIds': !exists(json, 'textAnalogyExampleIds') ? undefined : json['textAnalogyExampleIds'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'vectorSpaceId': !exists(json, 'vectorSpaceId') ? undefined : json['vectorSpaceId'],
    };
}

export function AnalogyDTOToJSON(value?: AnalogyDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'textAnalogyExampleIds': value.textAnalogyExampleIds,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'vectorSpaceId': value.vectorSpaceId,
    };
}

