/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataEntry } from './DataEntry';
import {
    DataEntryFromJSON,
    DataEntryFromJSONTyped,
    DataEntryToJSON,
} from './DataEntry';

/**
 * 
 * @export
 * @interface DataPage
 */
export interface DataPage {
    /**
     * 
     * @type {number}
     * @memberof DataPage
     */
    count?: number;
    /**
     * 
     * @type {Array<DataEntry>}
     * @memberof DataPage
     */
    elements?: Array<DataEntry>;
}

/**
 * Check if a given object implements the DataPage interface.
 */
export function instanceOfDataPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataPageFromJSON(json: any): DataPage {
    return DataPageFromJSONTyped(json, false);
}

export function DataPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'elements': !exists(json, 'elements') ? undefined : ((json['elements'] as Array<any>).map(DataEntryFromJSON)),
    };
}

export function DataPageToJSON(value?: DataPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'elements': value.elements === undefined ? undefined : ((value.elements as Array<any>).map(DataEntryToJSON)),
    };
}

