/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Modality } from './Modality';
import {
    ModalityFromJSON,
    ModalityFromJSONTyped,
    ModalityToJSON,
} from './Modality';

/**
 * 
 * @export
 * @interface DynamicAnalogyLookupRequestDto
 */
export interface DynamicAnalogyLookupRequestDto {
    /**
     * 
     * @type {Modality}
     * @memberof DynamicAnalogyLookupRequestDto
     */
    modality?: Modality;
    /**
     * The nth nearest index to the query
     * @type {number}
     * @memberof DynamicAnalogyLookupRequestDto
     */
    topK?: number;
    /**
     * 
     * @type {any}
     * @memberof DynamicAnalogyLookupRequestDto
     */
    query?: any;
    /**
     * Analogy from as binary data
     * @type {Array<Blob>}
     * @memberof DynamicAnalogyLookupRequestDto
     */
    start?: Array<Blob>;
    /**
     * Analogy to as binary data
     * @type {Array<Blob>}
     * @memberof DynamicAnalogyLookupRequestDto
     */
    end?: Array<Blob>;
}

/**
 * Check if a given object implements the DynamicAnalogyLookupRequestDto interface.
 */
export function instanceOfDynamicAnalogyLookupRequestDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DynamicAnalogyLookupRequestDtoFromJSON(json: any): DynamicAnalogyLookupRequestDto {
    return DynamicAnalogyLookupRequestDtoFromJSONTyped(json, false);
}

export function DynamicAnalogyLookupRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicAnalogyLookupRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modality': !exists(json, 'modality') ? undefined : ModalityFromJSON(json['modality']),
        'topK': !exists(json, 'top_k') ? undefined : json['top_k'],
        'query': !exists(json, 'query') ? undefined : json['query'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'end': !exists(json, 'end') ? undefined : json['end'],
    };
}

export function DynamicAnalogyLookupRequestDtoToJSON(value?: DynamicAnalogyLookupRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'modality': ModalityToJSON(value.modality),
        'top_k': value.topK,
        'query': value.query,
        'start': value.start,
        'end': value.end,
    };
}

