/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndexResponse
 */
export interface IndexResponse {
    /**
     * 
     * @type {string}
     * @memberof IndexResponse
     */
    status?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof IndexResponse
     */
    ids?: Array<number>;
}

/**
 * Check if a given object implements the IndexResponse interface.
 */
export function instanceOfIndexResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IndexResponseFromJSON(json: any): IndexResponse {
    return IndexResponseFromJSONTyped(json, false);
}

export function IndexResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
    };
}

export function IndexResponseToJSON(value?: IndexResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'ids': value.ids,
    };
}

