/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonTextLookupRequestDto
 */
export interface JsonTextLookupRequestDto {
    /**
     * The nth nearest index to the query
     * @type {number}
     * @memberof JsonTextLookupRequestDto
     */
    topK?: number;
    /**
     * Query as binary data
     * @type {string}
     * @memberof JsonTextLookupRequestDto
     */
    query?: string;
    /**
     * Optional list of ids to specify a query subset
     * @type {Array<number>}
     * @memberof JsonTextLookupRequestDto
     */
    ids?: Array<number>;
}

/**
 * Check if a given object implements the JsonTextLookupRequestDto interface.
 */
export function instanceOfJsonTextLookupRequestDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JsonTextLookupRequestDtoFromJSON(json: any): JsonTextLookupRequestDto {
    return JsonTextLookupRequestDtoFromJSONTyped(json, false);
}

export function JsonTextLookupRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonTextLookupRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'topK': !exists(json, 'topK') ? undefined : json['topK'],
        'query': !exists(json, 'query') ? undefined : json['query'],
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
    };
}

export function JsonTextLookupRequestDtoToJSON(value?: JsonTextLookupRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'topK': value.topK,
        'query': value.query,
        'ids': value.ids,
    };
}

