/* tslint:disable */
/* eslint-disable */
/**
 * Vecto API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vecto.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LookupResult } from './LookupResult';
import {
    LookupResultFromJSON,
    LookupResultFromJSONTyped,
    LookupResultToJSON,
} from './LookupResult';

/**
 * 
 * @export
 * @interface LookupResponse
 */
export interface LookupResponse {
    /**
     * 
     * @type {Array<LookupResult>}
     * @memberof LookupResponse
     */
    results?: Array<LookupResult>;
}

/**
 * Check if a given object implements the LookupResponse interface.
 */
export function instanceOfLookupResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LookupResponseFromJSON(json: any): LookupResponse {
    return LookupResponseFromJSONTyped(json, false);
}

export function LookupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LookupResultFromJSON)),
    };
}

export function LookupResponseToJSON(value?: LookupResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LookupResultToJSON)),
    };
}

